### ISSUE TITLE
请问放在Tomcat虚拟目录下，要怎样配置

### ISSUE THREAD

**Issue by EthanCo** [AdlerED/Picuang#3]
项目没有配置在Tomcat的主路径下，项目不是通过`http://localhost:8080`访问，而是通过`http://localhost:8080/picuang/`来访问，这个时候需要怎么配置。
发现html里的url依旧链接到`http://localhost:8080/favicon.png`，导致资源访问不到，正确能够访问的路径是`http://localhost:8080/picuang/favicon.png`

**Comment by adlered** [comment]
新版本将会改进，请关注v2.4。
